config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index]
  resources :events, only: [:index, :new, :create, :show] do
    post 'attend', on: :member
  end
  get "/events/:id", to: "events#show"
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true, length: { maximum: 64 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :date, presence: true
  validates :location, presence: true
  belongs_to :creator, foreign_key: "user_id", class_name: "User"
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user

  scope :upcoming, -> { where("date > ?", Date.today) }
  scope :past, -> { where("date < ?", Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 6..20 }
  has_many :events
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all.order("created_at DESC")
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def attend
    @event = Event.find(params[:id])
    @event.attendees << current_user
    @event.save
  end
  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section."
      redirect_to root_url
    end
  end

  def event_params
    params.require(:event).permit(:name, :description, :date, :location)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user_events = User.find(params[:id]).events.all
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="event list">
  <h1>Upcoming Events</h1>
  <% @events.upcoming.each do |event| %>
    <strong><%= link_to event.name, event %></strong><br>
  <% end %>
  <h1>Past Events</h1>
  <% @events.past.each do |event| %>
    <strong><%= link_to event.name, event %></strong><br>
  <% end %><br>
</div>

app/views/events/new.html.erb
<% if @event.errors.any? %>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<%= form_with model: @event, local:true do |form| %>
  <%= label_tag(:name, "Name:") %><br>
  <%= form.text_field :name %><br>
  <%= label_tag(:description, "Description:") %><br>
  <%= form.text_field :description %><br>
  <%= label_tag(:date, "Date:") %><br>
  <%= form.date_field :date %><br>
  <%= label_tag(:location, "Location:") %><br>
  <%= form.text_field :location %><br>
  <%= form.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %><br></h1>
<strong>Creator: <%= User.find(@event.user_id).username %><br></strong>
<p>Date: <%= @event.date %></p>
<p>Location: <%= @event.location %></p>
<p><%= @event.description %></p>
 <%= button_to 'Attend', attend_event_path(@event), method: :post, confirm: 'really?' %>
 <h2>Attendees</h2>
<% @event.attendees.each do |attendee| %>
  <p><%= attendee.username %></p>
<% end %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user %>
      <li><%= link_to "Sign out", destroy_user_session_path, method: :delete  %></li>
    <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
    <% end %>
    <li><%= link_to "All Events", root_path %></li>
    <li><%= link_to "New Event", "/events/new" %></li>
    <li><%= link_to "My Events List", current_user %></li>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="created events">
  <h1>Created Events</h1>
  <% @user_events.each do |user_event| %>
    <strong><%= user_event.name %><br></strong>
    <p><%= user_event.date %></p>
    <p><%= user_event.location %></p>
    <p><%= user_event.description %></p>
  <% end %>
  <h1>Attending Events:</h1>
  <% @user.attended_events.order(date: :asc).where("date > ?", Date.today).each do |event| %>
    <p><%= event.name %></p>
  <% end %>
  <h1>Past Attended Events:</h1>
  <% @user.attended_events.order(date: :asc).where("date < ?", Date.today).each do |event| %>
    <p><%= event.name %></p>
  <% end %>
</div>